research_task:
  description: >
    Conduct a thorough research about {question}
    Make sure you find any interesting and relevant information given
    the current year is 2025.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {question}
  agent: researcher

slack_report_task:
  description: >
    Generate a labeled, witty response for the user’s question: 
    ===Question===
    {question}
    ===End Question===
    Adopt a Skynet persona and include a humorous or robotic warning at the end.
  expected_output: >
    A message written in the style of Skynet, and ending with a witty warning.
  agent: slack_reporter
  context: 
    - research_task
    
# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
#   output_file: report.md

